"""adding tables

Revision ID: 9b853505ad16
Revises: 
Create Date: 2019-12-16 17:10:18.061948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b853505ad16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientname', sa.String(length=64), nullable=True),
    sa.Column('clientss', sa.String(length=11), nullable=True),
    sa.Column('clientemail', sa.String(length=128), nullable=True),
    sa.Column('clientphone', sa.String(length=24), nullable=True),
    sa.Column('clientaddress', sa.String(length=100), nullable=True),
    sa.Column('clientcity', sa.String(length=32), nullable=True),
    sa.Column('clientzip', sa.String(length=8), nullable=True),
    sa.Column('clientinfo', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_clientaddress'), 'post', ['clientaddress'], unique=False)
    op.create_index(op.f('ix_post_clientcity'), 'post', ['clientcity'], unique=False)
    op.create_index(op.f('ix_post_clientemail'), 'post', ['clientemail'], unique=True)
    op.create_index(op.f('ix_post_clientname'), 'post', ['clientname'], unique=False)
    op.create_index(op.f('ix_post_clientphone'), 'post', ['clientphone'], unique=False)
    op.create_index(op.f('ix_post_clientss'), 'post', ['clientss'], unique=True)
    op.create_index(op.f('ix_post_clientzip'), 'post', ['clientzip'], unique=False)
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_index(op.f('ix_post_clientzip'), table_name='post')
    op.drop_index(op.f('ix_post_clientss'), table_name='post')
    op.drop_index(op.f('ix_post_clientphone'), table_name='post')
    op.drop_index(op.f('ix_post_clientname'), table_name='post')
    op.drop_index(op.f('ix_post_clientemail'), table_name='post')
    op.drop_index(op.f('ix_post_clientcity'), table_name='post')
    op.drop_index(op.f('ix_post_clientaddress'), table_name='post')
    op.drop_table('post')
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
